### PR TITLE
Update base pod controller to support triggering actions

### PR DESCRIPTION
**Pull request by justinvdm**
We need to change the base pod controller to:
  - support triggering actions
  - fetch new pod data after an action has been triggered, and update the scope with the new data

### CODE REVIEW

**Comment by justinvdm** [comment]
@rudigiesler @KaitCrawford ready for review

**Comment by justinvdm** [comment]
(depends on #49)

**Comment by justinvdm** [comment]
@rudigiesler @KaitCrawford ready for review
@rowanseymour this PR will be making its way into a larger PR against upstream, just pinging you so its on your radar

**Comment by rudigiesler** [comment]
:+1:

**Pull request merged**
