### PR TITLE
Add sending outbound messages to Junebug endpoint

### PR DESCRIPTION
**Pull request by rudigiesler**

### CODE REVIEW

**Comment by rudigiesler** [comment]
@justinvdm @imsickofmaps Ready for review.

**Comment by justinvdm** [comment]
One minor comment, looks good.

**Comment by imsickofmaps** [comment]
@rudigiesler would you mind re-issuing this against https://github.com/praekelt/casepro/tree/EPIC-OPENHELPD-17 as per discussion yesterday?

**Comment by rudigiesler** [comment]
@imsickofmaps Yes I'll do that

**Comment by rudigiesler** [comment]
Superceded by https://github.com/praekelt/casepro/pull/13

**Pull request closed without merging**
