### PR TITLE
Improve pod display

### PR DESCRIPTION
**Pull request by KaitCrawford**
This fixes a few problems with the pod styles:
- [x] The default style for pods wasn't being loaded
- [x] When the site is open on a smaller screen the pods appear underneath the timeline and fill the width of the page. However, pod rows then wrap and the row value appears underneath the row name.
- [x] Currently there's no clear separation of rows so rows that wrap can become confusing.

### CODE REVIEW

**Comment by KaitCrawford** [comment]
Before:
unstriped_pod
unwrapped_pod

**Comment by KaitCrawford** [comment]
After:
striping
striped_pod
wrapping
wrapped_pod

**Comment by KaitCrawford** [comment]
Ready for review @justinvdm

**Comment by justinvdm** [comment]
:+1:

**Pull request merged**
