### PR TITLE
Refactored to use a set reassign_on datetime rather that calculating …

### PR DESCRIPTION
**Pull request by jpaidoussi**
Sets the expire time on the case on reassign.

### CODE REVIEW

**Comment by jpaidoussi** [comment]
@rudigiesler @KaitCrawford @smn Ready for review

**Comment by KaitCrawford** [comment]
@jpaidoussi I'm concerned about your change to the migrations. Since the original migrations have already been applied to staging won't changing them like this prevent the new changes from being applied to the database (since the db thinks it's already applied migration 0045)?

**Comment by jpaidoussi** [comment]
@KaitCrawford Yes, this change would break staging's DB. However, seeing as we are resetting staging's DB on Monday anyway I figured it would be better to regenerate the migration rather than have an extra one in the upstream PR.

**Comment by KaitCrawford** [comment]
In that case :+1:

**Pull request merged**
