### PR TITLE
Add export button for Users to the UI

### PR DESCRIPTION
**Pull request by smn**

### CODE REVIEW

**Comment by smn** [comment]
@KaitCrawford @rudigiesler @jpaidoussi ready for review

**Comment by rudigiesler** [comment]
Is there a reason we're comparing against staging? Staging tests are broken and can hide other test failures. Could we rather compare against another branch, and merge into staging after it lands?

**Comment by smn** [comment]
@rudigiesler right, let me see if I can change this against `develop` or `EPIC-OPENHELPD-20-case-counts`

**Comment by smn** [comment]
@rudigiesler right, thanks, I've changed it. Closing this one in favour of #108 -- please continue reviewing there?

**Pull request closed without merging**
