### PR TITLE
Provide visual feedback when pod actions are busy

### PR DESCRIPTION
**Pull request by justinvdm**
The plan is to grey out the button for a busy action, at the same time preventing users from triggering an action while it is busy.

### CODE REVIEW

**Comment by justinvdm** [comment]
@rudigiesler @KaitCrawford depends on #48, otherwise ready for review.

**Comment by justinvdm** [comment]
@rudigiesler ready for review

**Comment by rudigiesler** [comment]
:+1: , we must just remember to update the description and example here: https://github.com/praekelt/casepro/blob/EPIC-OPENHELPD-23/casepro/pods/base.py#L47-L62 , with the new busy text field

**Comment by justinvdm** [comment]
> :+1: , we must just remember to update the description and example here: https://github.com/praekelt/casepro/blob/EPIC-OPENHELPD-23/casepro/pods/base.py#L47-L62 , with the new busy text field

Thanks :) have created #61 for this.

**Pull request merged**
