### PR TITLE
Support optional confirmation modal for action triggers

### PR DESCRIPTION
**Pull request by justinvdm**
The plan is to support an optional `confirm` flag on actions, and make use of a confirmation modal for actions where the flag is `true`.

### CODE REVIEW

**Comment by justinvdm** [comment]
Depends on #60, otherwise ready for review.

**Comment by justinvdm** [comment]
@rowanseymour This PR adds confirmation modals in a slightly different way to how they are currently done in casepro, so I thought I should ping you to get your thoughts. I've added a [service](https://github.com/praekelt/casepro/compare/feature/issue-60-show-when-pods-load-or-fail-to-load...praekelt:feature/issue-58-pod-confirm-modal#diff-605d5fe78f6a6aac57fb0e52c1ecceb3R554) that makes use of a [single template](https://github.com/praekelt/casepro/compare/feature/issue-60-show-when-pods-load-or-fail-to-load...praekelt:feature/issue-58-pod-confirm-modal#diff-605d5fe78f6a6aac57fb0e52c1ecceb3R554) for defining the modal based on some context we give (it switches on the ``type`` we give it to determine how to render the modal). The reason for doing it this way was to keep all markup and copy inside templates rather than embedded in the scripts.

Seeing as this is quite a different approach, I'd be happy to rather make use of the current approach for confirmation modals if you prefer, but thought I'd first show the approach I'd like to take here.

Side note: This PR depends on another PR, so looking at the diff directly might not show the approach that well, but I've made a [compare view](https://github.com/praekelt/casepro/compare/feature/issue-60-show-when-pods-load-or-fail-to-load...praekelt:feature/issue-58-pod-confirm-modal) if you'd like to take a look at what is added in this particular PR.

**Comment by rowanseymour** [comment]
@justinvdm the current modal stuff is far from ideal and I've often wanted to start again with a service dedicated to modals, to replace `UtilsService` which has evolved into one of those "not sure where else to put this" classes. If we can come up with a new approach that can cover what is already done by `UtilsService.xyzModal(..)` then I'd rather start replacing that, than have pods use a different modal system than the rest of the application.

One thing I'm not quite getting yet is how plugins provide new confirmation dialog types if the templates are all bundled into _case-confirm-modals.html_

What if we had a generic confirm modal, which can take an optional template for the prompt part which may include markup, e.g.

```javascript
Modals.confirm({prompt: "You sure?"})
Modals.confirm({promptTemplateUrl: "/foo/confirm-bar.html", promptContext: {...}})
```

That way it's still simple for the common case of wanting to use different prompt strings with no markup. I feel like _"Are you sure you want to perform this action?"_ is a bit vague, but creating whole new templates for every _"Are you sure you want to ... ?" possibility would get annoying.

Sorta related to this topic, do you guys foresee a need to ever make the CasePro UI translatable?

**Comment by justinvdm** [comment]
@rowanseymour thanks for the feedback :)

> One thing I'm not quite getting yet is how plugins provide new confirmation dialog types if the templates are all bundled into case-confirm-modals.html

Hmm, good point, only thought about the bundled pod implementation for this tbh.

> I feel like "Are you sure you want to perform this action?" is a bit vague, but creating whole new templates for every "Are you sure you want to ... ?" possibility would get annoying.

Since we already have each action's name in the modal's title, it seemed to be clear enough what the modal was about. We could probably also support an optional field for each action to provide text for the confirm question to ask, but to keep things simple for now I'd like to see if the title makes it clear enough.

> What if we had a generic confirm modal, which can take an optional template for the prompt part which may include markup, e.g.

Modals.confirm({prompt: "You sure?"})
Modals.confirm({promptTemplateUrl: "/foo/confirm-bar-prompt.html", promptContext: {...}})


I like that idea, +1 :) Will change the current approach to something like that.

> Sorta related to this topic, do you guys foresee a need to ever make the CasePro UI translatable?

Good question, I can see its relevance, since keeping copy in angular templates is likely to make that tricky to do. We don't have any current plans I don't think, but for the longer term I think the answer is yes. From the discussion we had on rapidpro/casepro#107, I understand we could serve templates as partials that make use of django's internationalization tools. The tricky thing here is being able to test the angular parts of the UI that use templates. We aren't able to use the templates in angular tests (unless we have the server-side running for angular tests, which sounds a bit like overkill but maybe is worth considering?). It is possible to stub away the templates in tests, but I think that makes for weaker tests and would like to avoid that route.

**Comment by rowanseymour** [comment]
Obviously you guys are free to implement your plugins as you see fit but if/when we replace other confirmation modals (and I hope we do), I think I'd still lean toward more specific prompt messages. For example we have prompts like

_"Archive the selected messages? This will remove them from your inbox."_ 
_"Restore the selected messages? This will put them back in your inbox."_

which summarise the action and the consequences. 

We also style ones for deleting things with red buttons to strike fear into the hearts of our users. So maybe this `Modals.confirm` needs params for title and style (maybe just `danger: true|false` ?) etc.

Re translation... a while back I also tried the haml > html2js route but gave up and that's why our current modals are not as throughly tested as they might be. We haven't been specifically asked to provide translation for UPartners so am happy to go with html templates for now. Feels good seeing templates tested.

Maybe in future, if it is needed, we could have html Django templates with only `trans` tags. html2js might be ok with that, or we write something simple to convert the `trans` tags ourselves. Running a full django server would definitely feel like overkill.

**Comment by justinvdm** [comment]
@rudigiesler I've created #62 to change to the approach discussed in the comments here, I think it'll be easier to first land this to epic branch 23, and make a new PR for #62, so this PR is still ready for review.

**Comment by justinvdm** [comment]
@rudigiesler ready for review

**Comment by rudigiesler** [comment]
:+1: from me

**Pull request merged**
