### PR TITLE
Feature/OPENHELPD-101 change to replying to a message

### PR DESCRIPTION
**Pull request by jpaidoussi**

### CODE REVIEW

**Comment by jpaidoussi** [comment]
@rudigiesler Ready for review

**Comment by rudigiesler** [comment]
Looks good to me. Do we maybe want tests? Also, I'm not sure we want to merge this into our develop branch. Maybe have this PR go straight to upstream?

**Comment by jpaidoussi** [comment]
@rudigiesler My thinking was to merge it into staging when you are happy with the PR for QA testing once once passed there change the base of this PR to be directly upstream.

**Comment by jpaidoussi** [comment]
@rowanseymour Ready for you to look over.

**Comment by rowanseymour** [comment]
👍

**Pull request merged**
